# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  site-url: https://mohamedketeb.github.io
  title: "Mohamed M. Keteb"                                # Your name
  description: "Gandalf is a renowned wizard and scholar of Middle-earth"   # A brief slogan (optional)
  image: img/my_image.jpg
  
  # favicon: img/favicon.png (removed)
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    # logo: /img/logo.png (supprimé pour ne pas afficher de logo dans la bannière)
    
    # your sub-pages
    left:
      - text: "Teaching"
        href: teaching/index.qmd
      - text: "Publications"
        href: publications/index.qmd
      - text: "Talks"
        href: talks/index.qmd
      - text: "Photos"
        href: photos/index.qmd
      - text: "CV"
        href: cv/index.qmd
    right:
      - icon: github
        href: https://github.com/MohamedKeteb
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/mohamed-mehdi-keteb-782258229
        aria-label: LinkedIn
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: overlay
  page-footer: 
    left: ""
    center: |
      <span class="faux-block">Mohamed Keteb's website</span>
    right: ""

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
